version: '3.8'
services:
  app:
    build: .
    container_name: botjs
    ports:
      - '8080:8080'
    volumes:
      - ./src:/app
      - /app/node_modules
    tty: true
    env_file:
      - .env